run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/ottodashadow/lego-consul
  maligned:
    suggest-new: true

linters:
  enable:
    - goconst
    - errcheck
    - gofmt
    - goimports
    - golint
    - unconvert
    - unparam
    - bodyclose
    - gocyclo
    - misspell
    - maligned
    - whitespace