name: Release

on:
  push:
    tags: 'v*'

env:
  GO_VERSION: 1.19.1

jobs:
  create-release:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Gather Build Info
        id: build_info
        run: |
          echo ::set-output name=BUILD_COMMIT::`git describe --always --dirty`
          echo ::set-output name=BUILD_DATE::`date -u +%FT%TZ`
          echo ::set-output name=BUILD_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build for Linux/macOS
        run: go build -ldflags "-s -w -X ${INJECT_VERSION} -X ${INJECT_COMMIT} -X ${INJECT_DATE}" -o bin/lego-consul main/main.go
        env:
          CGO_ENABLED: 0
          INJECT_VERSION: "github.com/feedonomics/lego-consul/version.version=${{ steps.build_info.outputs.BUILD_VERSION }}"
          INJECT_COMMIT: "github.com/feedonomics/lego-consul/version.commit=${{ steps.build_info.outputs.BUILD_COMMIT }}"
          INJECT_DATE: "github.com/feedonomics/lego-consul/version.built=${{ steps.build_info.outputs.BUILD_DATE }}"

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/lego-consul
          asset_name: lego_consul_${{ steps.build_info.outputs.BUILD_VERSION }}_linux_x86_64
          asset_content_type: application/octet-stream